### PR TITLE
Feature: Add support for PHP 8; Change phpunit to 9.5

### PR DESCRIPTION
**Pull request by jchodzicki**

### CODE REVIEW

**Comment by dducro** [comment]
Please merge this PR

**Comment by jchodzicki** [comment]
Hey,
I have no write access :(

wt., 15 cze 2021 o 20:31 Daniël Ducro ***@***.***> napisał(a):

**Comment by nullpunkt** [comment]
Hey! Thank you for the upgrade. Did you check if your fix also works with PHP Versions <=7 ? There should be at least support for PHP 6 and 7.

**Comment by dducro** [comment]
I confirm this version works om 7.4

**Comment by jchodzicki** [comment]
> Hey! Thank you for the upgrade. Did you check if your fix also works with PHP Versions <=7 ? There should be at least support for PHP 6 and 7.

https://www.php.net/supported-versions.php
This will be working on supported versions.

**Pull request merged**
